version: '3.8'
services:
  flask-app:
    image: flask-app
    build: ./flask-app
    depends_on:
      - mysql
  mysql:
    image: flask-db
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=${SECRET_KEY}
      - MYSQL_DATABASE=${DATABASE_URI}
  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - flask-app