version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: cne-sfia2-project-frontend:latest
    ports:
      - target: 5000
        published: 5000
    volumes:
      - ./frontend:/var/frontend
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./backend
    image: cne-sfia2-project-backend:latest
    ports:
      - target: 5001
        published: 5001
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./backend:/backend-data
    depends_on:
      - database
  database:
    container_name: database
    image: cne-sfia2-project-database:latest
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=${SECRET_KEY}
      - MYSQL_DATABASE=${DATABASE_URI}
    volumes:
      - ./database:/database
    depends_on:
      - backend
  nginx:
    build: nginx.conf
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      default:
        - aliases:
            - ${HOSTNAME}

  networks:
    default: