version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: cne-sfia2-project-frontend:latest
    ports:
      - target: 5000
        published: 5000
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./backend
    image: cne-sfia2-project-backend:latest
    ports:
      - target: 5001
        published: 5001
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./backend:/backend
    depends_on:
      - database
  database:
    container_name: database
    image: cne-sfia2-project-database:latest
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_URI}
    volumes:
      - ./database:/database
    depends_on:
      - backend
  nginx:
    image: library/nginx:latest
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend