version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: cne-sfia2-project-frontend:latest
    ports:
      - target: 5000
        published: 5000
  backend:
    container_name: backend
    build: ./backend
    image: cne-sfia2-project-backend:latest
    ports:
      - target: 5001
        published: 5001
  mysql:
    container_name: db
    image: cne-sfia2-project-db:latest
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=${SECRET_KEY}
      - MYSQL_DATABASE=${DATABASE_URI}
  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontends