version: '3.8'
services:
  frontend:
    container_name: front
    build: ./frontend
    image: dkhan20/frontend
    ports:
      - target: 5000
        published: 5000
    depends_on:
      - backend

  backend:
    container_name: back
    build: ./backend
    image: dkhan20/backend
    environment:
      - MYSQL_DATABASE=database
      - TEST_DATABASE_URI=${TEST_DATABASE_URI}
      - DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - target: 5001
        published: 5001

  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend


