version: '3.8'
services:
  frontend:
    container_name: front
    build: ./frontend
    image: frontend:${app_version}

  backend:
    container_name: back
    build: ./backend
    image: backend:${app_version}
    environment:
      - MYSQL_DATABASE=database
      - DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_ROOT_PASSWORD=${SECRET_KEY}

  database:
    container_name: db
    image: mysql:${app_version}
    build: ./database
    environment:
      - MYSQL_DATABASE=database
      - DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_ROOT_PASSWORD=${SECRET_KEY}
  nginx:
    build: nginx
    image: nginx:latest
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend