version: '3.8'
services:
  frontend:
    container_name: front
    build: ./frontend
    image: dkhan20/frontend:${app_version}
    ports:
      - target: 5000
        published: 5000
    depends_on:
      - backend
  backend:
    container_name: back
    build: ./backend
    image: dkhan20/backend:${app_version}
    environment:
      - MYSQL_DATABASE=database
      - DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_ROOT_PASSWORD=${SECRET_KEY}
    ports:
      - target: 5001
        published: 5001
    depends_on:
      - database

  database:
    container_name: db
    image: dkhan20/database:${app_version}
    build: ./database
    environment:
      - MYSQL_DATABASE=database
      - DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_ROOT_PASSWORD=${SECRET_KEY}
  nginx:
    build: nginx
    image: nginx:latest
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend