version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend:latest
  backend:
    container_name: backend
    build: ./backend
    image: backend:latest
    environment:
      - SECRET_KEY=${SECRET_KEY}
  database:
    container_name: database
    image: database:latest
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=${SECRET_KEY}
      - MYSQL_DATABASE=${DATABASE_URI}

  nginx:
    build: nginx
    image: nginx:latest
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend