version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend:latest

  backend:
    container_name: backend
    build: ./backend
    image: backend:latest


  database:
    container_name: database
    image: mysql:latest
    build: ./database
    environment:
      - MYSQL_DATABASE=database
      - DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_ROOT_PASSWORD=${SECRET_KEY}
    volumes:
      - "./sito/database/:/var/lib/database"
  nginx:
    build: nginx
    image: nginx:latest
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend