apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      index frontend/application/templates/index.html;
      location / {
          proxy_pass  http://frontend:5000/;
      }
    }