# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
    - name: database
      port: 3306
  type: ClusterIP
---
# Client service for connecting to any MySQL instance for reads.
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - image: dkhan20/database:latest
          name: database
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ${MYSQL_ROOT_PASSWORD}
            - name: DB_PASSWORD
              value: ${DB_PASSWORD}
            - name: TEST_DATABASE_URI
              value: ${TEST_DATABASE_URI}
            - name: DATABASE_URI
              value: ${DATABASE_URI}
            - name: SECRET_KEY
              value: ${SECRET_KEY}
          ports:
            - containerPort: 3306
              name: database