apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: dkhan20/database
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: password
              # Use secret in real usage
            - name: DB_PASSWORD
              value: password
            # Use secret in real usage
            - name: TEST_DATABASE_URI
              value: mysql+pymysql://admin:password@testdb.cgytirb7uezx.eu-west-2.rds.amazonaws.com:3306/testdb
            # Use secret in real usage
            - name: DATABASE_URI
              value: mysql+pymysql://admin:password@deploydb.cgytirb7uezx.eu-west-2.rds.amazonaws.com:3306/users
            - name: SECRET_KEY
              value: password

          ports:
            - containerPort: 3306
          readinessProbe:
            httpGet:
              path: /database
              port: 3306
      volumes:
        - name: database-config
          configMap:
            name: database-config