---
- name: Install Jenkins on Jenkins vm
  hosts: jenkins
  gather_facts: false
  become: true
  tasks:
    - import_role:
        name: jenkins
    - name: Install docker and docker-compose
      script: Dockerfile.sh

- name: Configure Test vm
  hosts: testvm
  tasks:
    - name: Install docker and docker-compose
      script: Dockerfile.sh

- name: Configure k8s on deploy vm
  hosts: K8S_CLuster
  become: true
  tasks:
    - import_role:
        name: k8s-cluster
