---
- name: Install Jenkins on Jenkins vm
  hosts: jenkins
  gather_facts: false
  become: true
  tasks:
    - import_role:
        name: jenkins

- name: Install Docker in Test vm
  hosts: testvm
  tasks:
    - import_role:
        name: docker
    -import_role:
        name: docker-compose
